//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSachLaKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonHang
    {
        public string MaSach { get; set; }
        public string MaDH { get; set; }
        public int SoLuongMua { get; set; }
        public decimal GiaTien { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
