//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSachLaKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        public string MaDH { get; set; }
        public System.DateTime NgayDH { get; set; }
        public decimal GiaDH { get; set; }
        public System.DateTime NgayGiaoHang { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChiGiao { get; set; }
        public int SdtNguoiNhan { get; set; }
        public string TenNguoiGiao { get; set; }
        public string SdtNguoiGiao { get; set; }
        public string HinhThucGiao { get; set; }
        public string MaKH { get; set; }
        public string MaHTTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
    }
}
