//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanSachLaKho.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string KichThuoc { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public decimal GiaBia { get; set; }
        public decimal DonGia { get; set; }
        public int SoLuongSach { get; set; }
        public string MoTaSach { get; set; }
        public string HinhSach { get; set; }
        public string MaNXB { get; set; }
        public string MaTG { get; set; }
        public string MaTheLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
